In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('C:/Users/welcome/OneDrive/Desktop/googleplaystore.csv')

In [3]:
print(data)

                                                     App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN
1                                    Coloring book moana       ART_AND_DESIGN
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN
3                                  Sketch - Draw & Paint       ART_AND_DESIGN
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN
...                                                  ...                  ...
10836                                   Sya9a Maroc - FR               FAMILY
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY
10838                             Parkinson Exercices FR              MEDICAL
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE

       Rating Reviews                Size     Installs  Type Price  \
0         4.1     159                 19M      10,000+  Free     0
1         3.9     967                 14M     500,000+  Free     0
2         4.7   87510                8.7M   5,000,000+  Free     0
3         4.5  215644                 25M  50,000,000+  Free     0
4         4.3     967                2.8M     100,000+  Free     0
...       ...     ...                 ...          ...   ...   ...
10836     4.5      38                 53M       5,000+  Free     0
10837     5.0       4                3.6M         100+  Free     0
10838     NaN       3                9.5M       1,000+  Free     0
10839     4.5     114  Varies with device       1,000+  Free     0
10840     4.5  398307                 19M  10,000,000+  Free     0

      Content Rating                     Genres Last Updated  \
0           Everyone               Art & Design     7-Jan-18
1           Everyone  Art & Design;Pretend Play    15-Jan-18
2           Everyone               Art & Design     1-Aug-18
3               Teen               Art & Design     8-Jun-18
4           Everyone    Art & Design;Creativity    20-Jun-18
...              ...                        ...          ...
10836       Everyone                  Education    25-Jul-17
10837       Everyone                  Education     6-Jul-18
10838       Everyone                    Medical    20-Jan-17
10839     Mature 17+          Books & Reference    19-Jan-15
10840       Everyone                  Lifestyle    25-Jul-18

              Current Ver         Android Ver
0                   1.0.0        4.0.3 and up
1                   2.0.0        4.0.3 and up
2                   1.2.4        4.0.3 and up
3      Varies with device          4.2 and up
4                     1.1          4.4 and up
...                   ...                 ...
10836                1.48          4.1 and up
10837                   1          4.1 and up
10838                   1          2.2 and up
10839  Varies with device  Varies with device
10840  Varies with device  Varies with device

[10841 rows x 13 columns]

In [4]:
data.head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,7-Jan-18,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,15-Jan-18,2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,1-Aug-18,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,8-Jun-18,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,20-Jun-18,1.1,4.4 and up

In [5]:
data.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,25-Jul-17,1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,6-Jul-18,1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,20-Jan-17,1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,19-Jan-15,Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,25-Jul-18,Varies with device,Varies with device

In [6]:
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [7]:
data[data['Rating'] == data['Rating'].max()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,11-Feb-18,1.0.19,4.0 and up,NaN

In [8]:
data[data['Rating'] == data['Rating'].min()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
625,House party - live chat,DATING,1.0,1,9.2M,10+,Free,0,Mature 17+,Dating,31-Jul-18,3.52,4.0.3 and up
4127,Speech Therapy: F,FAMILY,1.0,1,16M,10+,Paid,$2.99,Everyone,Education,7-Oct-16,1,2.3.3 and up
5151,Clarksburg AH,MEDICAL,1.0,1,28M,50+,Free,0,Everyone,Medical,1-May-17,300000.0.81,4.0.3 and up
5978,Truck Driving Test Class 3 BC,FAMILY,1.0,1,2.0M,50+,Paid,$1.49,Everyone,Education,9-Apr-12,1,2.1 and up
6319,BJ Bridge Standard American 2018,GAME,1.0,1,4.9M,"1,000+",Free,0,Everyone,Card,21-May-18,6.2-sayc,4.0 and up
6490,MbH BM,MEDICAL,1.0,1,2.3M,100+,Free,0,Everyone,Medical,14-Dec-16,1.1.3,4.3 and up
7144,CB Mobile Biz,FINANCE,1.0,3,8.4M,500+,Free,0,Everyone,Finance,22-Feb-16,4.4.1255,4.0 and up
7383,Thistletown CI,PRODUCTIVITY,1.0,1,6.6M,100+,Free,0,Everyone,Productivity,15-Mar-18,41.9,4.1 and up
7427,CJ DVD Rentals,COMMUNICATION,1.0,5,13M,100+,Free,0,Everyone,Communication,6-Oct-17,1,4.1 and up
7806,CR Magazine,BUSINESS,1.0,1,7.8M,100+,Free,0,Everyone,Business,23-Jul-14,2.4.2,2.3.3 and up
7926,Tech CU Card Manager,FINANCE,1.0,2,7.2M,"1,000+",Free,0,Everyone,Finance,25-Jul-17,1.0.1,4.0 and up
8820,DS Creator 2.0,TOOLS,1.0,2,4.4M,500+,Free,0,Everyone,Tools,23-Mar-18,2.0.180226.1,4.0 and up
8875,DT future1 cam,TOOLS,1.0,1,24M,50+,Free,0,Everyone,Tools,27-Mar-18,3.1,2.2 and up
10324,FE Mechanical Engineering Prep,FAMILY,1.0,2,21M,"1,000+",Free,0,Everyone,Education,27-Jul-18,5.33.3669,5.0 and up
10400,Familial Hypercholesterolaemia Handbook,MEDICAL,1.0,2,33M,100+,Free,0,Everyone,Medical,2-Jul-18,2.0.1,4.1 and up
10591,Lottery Ticket Checker - Florida Results & Lotto,TOOLS,1.0,3,41M,500+,Free,0,Everyone,Tools,12-Dec-17,1,4.2 and up

In [9]:
# To check how many rows and columns present in our dataset
data.shape

(10841, 13)

In [10]:
print('Number of Rows', data.shape[0])
print('Number of Columns', data.shape[1])

Number of Rows 10841
Number of Columns 13

In [11]:
# To get the information about the dataset like Total Number Rows, Total Number of Columns, Datatypes of each column and memory Requirement
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [12]:
# Get the overall statistics of the dataset
data.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

### In dataset having only Rating Numerical values

In [13]:
# If i get overall dataset statistics than
data.describe(include = 'all')

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,9367.000000,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,NaN,6002,462,22,3,93,6,120,1378,2784,33
top,ROBLOX,FAMILY,NaN,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,3-Aug-18,Varies with device,4.1 and up
freq,9,1972,NaN,596,1695,1579,10039,10040,8714,842,326,1459,2451
mean,NaN,NaN,4.193338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.537431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,4.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Total number of App Title that contains Astrology
data[data['App'].str.contains('Astrology', case = False)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1570,Horoscopes – Daily Zodiac Horoscope and Astrology,LIFESTYLE,4.6,161143,11M,"10,000,000+",Free,0,Everyone 10+,Lifestyle,25-Jun-18,5.2.4(881),4.0.3 and up
1592,သိင်္ Astrology - Min Thein Kha BayDin,LIFESTYLE,4.7,2225,15M,"100,000+",Free,0,Everyone,Lifestyle,26-Jul-18,4.2.1,4.0.3 and up
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,25-Jul-18,Varies with device,Varies with device

In [15]:
len(data[data['App'].str.contains('Astrology', case  = False)])

3

In [16]:
# To find the App rating
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [17]:
data['Rating']

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10836    4.5
10837    5.0
10838    NaN
10839    4.5
10840    4.5
Name: Rating, Length: 10841, dtype: float64

In [18]:
# Find The Average App Rating
data['Rating'].mean()

4.193338315362443

In [19]:
data['Rating'].max()

19.0

In [20]:
data['Rating'].min()

1.0

In [21]:
# Find The total number of Unique Cotegory
data['Category']

0             ART_AND_DESIGN
1             ART_AND_DESIGN
2             ART_AND_DESIGN
3             ART_AND_DESIGN
4             ART_AND_DESIGN
                ...
10836                 FAMILY
10837                 FAMILY
10838                MEDICAL
10839    BOOKS_AND_REFERENCE
10840              LIFESTYLE
Name: Category, Length: 10841, dtype: object

In [22]:
data['Category'].nunique()

34

In [23]:
# Which Category has getting the highest rating
data.groupby('Category')['Rating'].mean().sort_values(ascending = False)

Category
1.9                    19.000000
EVENTS                  4.435556
EDUCATION               4.389032
ART_AND_DESIGN          4.358065
BOOKS_AND_REFERENCE     4.346067
PERSONALIZATION         4.335987
PARENTING               4.300000
GAME                    4.286326
BEAUTY                  4.278571
HEALTH_AND_FITNESS      4.277104
SHOPPING                4.259664
SOCIAL                  4.255598
WEATHER                 4.244000
SPORTS                  4.223511
PRODUCTIVITY            4.211396
HOUSE_AND_HOME          4.197368
FAMILY                  4.192272
PHOTOGRAPHY             4.192114
AUTO_AND_VEHICLES       4.190411
MEDICAL                 4.189143
LIBRARIES_AND_DEMO      4.178462
FOOD_AND_DRINK          4.166972
COMMUNICATION           4.158537
COMICS                  4.155172
NEWS_AND_MAGAZINES      4.132189
FINANCE                 4.131889
ENTERTAINMENT           4.126174
BUSINESS                4.121452
TRAVEL_AND_LOCAL        4.109292
LIFESTYLE               4.094904
VIDEO_PLAYERS           4.063750
MAPS_AND_NAVIGATION     4.051613
TOOLS                   4.047411
DATING                  3.970769
Name: Rating, dtype: float64

In [24]:
# find Total number of apps having 5 star Rating
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [25]:
data['Rating'] == 5.0

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837     True
10838    False
10839    False
10840    False
Name: Rating, Length: 10841, dtype: bool

In [26]:
data[data['Rating'] == 5]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
329,Hojiboy Tojiboyev Life Hacks,COMICS,5.0,15,37M,"1,000+",Free,0,Everyone,Comics,26-Jun-18,2,4.0.3 and up
612,American Girls Mobile Numbers,DATING,5.0,5,4.4M,"1,000+",Free,0,Mature 17+,Dating,17-Jul-18,3,4.0.3 and up
615,Awake Dating,DATING,5.0,2,70M,100+,Free,0,Mature 17+,Dating,24-Jul-18,2.2.9,4.4 and up
633,Spine- The dating app,DATING,5.0,5,9.3M,500+,Free,0,Teen,Dating,14-Jul-18,4,4.0.3 and up
636,Girls Live Talk - Free Text and Video Chat,DATING,5.0,6,5.0M,100+,Free,0,Mature 17+,Dating,1-Aug-18,8.2,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10721,Mad Dash Fo' Cash,GAME,5.0,14,16M,100+,Free,0,Everyone,Arcade,19-Jun-17,2.5a,4.1 and up
10742,GKPB FP Online Church,LIFESTYLE,5.0,32,7.9M,"1,000+",Free,0,Everyone,Lifestyle,31-Dec-17,0.7.1,4.4 and up
10776,Monster Ride Pro,GAME,5.0,1,24M,10+,Free,0,Everyone,Racing,5-Mar-18,2,2.3 and up
10820,Fr. Daoud Lamei,FAMILY,5.0,22,8.6M,"1,000+",Free,0,Teen,Education,27-Jun-18,3.8.0,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,6-Jul-18,1,4.1 and up

In [27]:
len(data[data['Rating'] == 5])
# So this much of category having the 5 star rating

274

In [28]:
data[data['Reviews'] =='3.0M']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,11-Feb-18,1.0.19,4.0 and up,NaN

In [29]:
data['Reviews'] =data['Reviews'].replace('3.0M', 3.0)

In [30]:
data['Reviews'] = data['Reviews'].astype('float')

In [31]:
data['Reviews'].dtype
# So here the type is Object type

dtype('float64')

In [32]:
avg_reviews = data['Reviews'].mean()

In [33]:
print('So this much of the average reviews :',avg_reviews)

So this much of the average reviews : 444111.9265750392

In [34]:
# To find the no of Free and Paid apps
data['Type'].value_counts()

Type
Free    10039
Paid      800
0           1
Name: count, dtype: int64

In [35]:
# Which app having the highest Reviews
data['Reviews']

0           159.0
1           967.0
2         87510.0
3        215644.0
4           967.0
           ...
10836        38.0
10837         4.0
10838         3.0
10839       114.0
10840    398307.0
Name: Reviews, Length: 10841, dtype: float64

In [36]:
data['Reviews'].max()

78158306.0

In [40]:
data[data['Reviews'].max()== data['Reviews']]
# So this row having the maximum reviews

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2544,Facebook,SOCIAL,4.1,78158306.0,Varies with device,"1,000,000,000+",Free,0,Teen,Social,3-Aug-18,Varies with device,Varies with device

In [41]:
data[data['Reviews'].max() == data['Reviews']]['App']
# So the Facebook App having the heighest Reviews

2544    Facebook
Name: App, dtype: object

In [42]:
# To Display top 5 Apps that having the heighest Reviews
data['Reviews'].sort_values(ascending = False).head()

2544    78158306.0
3943    78128208.0
381     69119316.0
336     69119316.0
3904    69109672.0
Name: Reviews, dtype: float64

In [43]:
# Bottoms reviews
data['Reviews'].sort_values(ascending = False).tail()

9713    0.0
8495    0.0
6277    0.0
8489    0.0
5086    0.0
Name: Reviews, dtype: float64

In [47]:
index = data['Reviews'].sort_values(ascending = False).head().index

In [48]:
data.iloc[index]['App']

2544              Facebook
3943              Facebook
381     WhatsApp Messenger
336     WhatsApp Messenger
3904    WhatsApp Messenger
Name: App, dtype: object

In [50]:
data.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,"10,000+",Free,0,Everyone,Art & Design,7-Jan-18,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,15-Jan-18,2.0.0,4.0.3 and up

In [53]:
data.groupby('Type')['Rating'].mean()

Type
0       19.000000
Free     4.186203
Paid     4.266615
Name: Rating, dtype: float64

In [54]:
# Display top 5 app that having max install
data['Installs']

0            10,000+
1           500,000+
2         5,000,000+
3        50,000,000+
4           100,000+
            ...
10836         5,000+
10837           100+
10838         1,000+
10839         1,000+
10840    10,000,000+
Name: Installs, Length: 10841, dtype: object

In [57]:
data['Installs'].dtype

dtype('O')

In [58]:
data['Installs_1'] = data['Installs'].str.replace(',', '')

In [83]:
data['Install_1'] = data['Installs_1'].str.replace('+','')

In [84]:
data.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_1,Install_1
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,"10,000+",Free,0,Everyone,Art & Design,7-Jan-18,1.0.0,4.0.3 and up,"10,000+","10,000"
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,15-Jan-18,2.0.0,4.0.3 and up,"500,000+","500,000"

In [85]:
data[data['Installs'] =='Free']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_1,Install_1
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0,"1,000+",Free,0,Everyone,NaN,11-Feb-18,1.0.19,4.0 and up,NaN,0,0

In [88]:
data['Installs_1'] = data['Installs_1'].str.replace('free','0')

In [91]:
data['Installs_1'].dtype

dtype('O')

In [93]:
index = data['Installs_1'].sort_values(ascending = False).head().index

In [95]:
data.iloc[index]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_1,Install_1
1661,Temple Run 2,GAME,4.3,8118609.0,62M,"500,000,000+",Free,0,Everyone,Action,5-Jul-18,1.49.1,4.0 and up,"500,000,000+","500,000,000"
4039,Google Duo - High Quality Video Calls,COMMUNICATION,4.6,2083237.0,Varies with device,"500,000,000+",Free,0,Everyone,Communication,31-Jul-18,37.1.206017801.DR37_RC14,4.4 and up,"500,000,000+","500,000,000"
385,Viber Messenger,COMMUNICATION,4.3,11334973.0,Varies with device,"500,000,000+",Free,0,Everyone,Communication,18-Jul-18,Varies with device,Varies with device,"500,000,000+","500,000,000"
3562,Google Calendar,PRODUCTIVITY,4.2,858230.0,Varies with device,"500,000,000+",Free,0,Everyone,Productivity,6-Aug-18,Varies with device,Varies with device,"500,000,000+","500,000,000"
4048,Dropbox,PRODUCTIVITY,4.4,1860844.0,61M,"500,000,000+",Free,0,Everyone,Productivity,1-Aug-18,Varies with device,Varies with device,"500,000,000+","500,000,000"

In [96]:
data.iloc[index]['App']

1661                             Temple Run 2
4039    Google Duo - High Quality Video Calls
385                           Viber Messenger
3562                          Google Calendar
4048                                  Dropbox
Name: App, dtype: object